application:
  name: Repose comparison app
  description: Repose comparison app application.  Just an example of how to compare two tests in 1 container
  location: apps/repose_comparison_app/bootstrap.rb
  type: comparison
  plugins:
   - location: plugins/repose_jmx_plugin/plugin.rb
  sub_apps: 
   - 
     id: main
     name: Main application
     description: This is the base configuration for Repose
